spring:
    application:
        name: card-microservice
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 0

eureka:
    client:
        serviceUrl:
            defaultZone: http://user:password@localhost:8761/eureka/
    instance:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
    queues:
        card-emission: card-emission

management:
    endpoints:
        web:
            exposure:
                include: '*'

logging:
    file:
        name: ./logs/log-file.log