spring:
    application:
        name: eurekaserver
    security:
        basic:
            enabled: true
        user:
            name: user
            password: 1234

server:
    port: 8761

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false